[Fix] User is not able to target hidden menus with TAB
Fliplet/fliplet-menu-circle pull request #20
Opened 2020-09-03 13:54 UTC by MaksymShokin

@sofiiakvasnevska

## Issue
Fliplet/fliplet-studio#6420

## Description
Active will change the display from none to block.

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2020-09-04 16:10 UTC, tonytlwu commented
@MaksymShokin Can you add a screencast for how the menu expands and collapses before and after this change? I believe the transforms were used to facilitate a smooth animation.

2020-09-05 21:29 UTC, MaksymShokin commented
@tonytlwu 
Circle menu seems fine to me https://streamable.com/z4yajl

2020-09-07 13:41 UTC, tonytlwu commented
@MaksymShokin You need to compare how this works in production. For example, you can see that there's a change in transition here https://share.getcloudapp.com/YEuow6BD

Please provide the same comparison for https://github.com/Fliplet/fliplet-menu-sequential/pull/18 and https://github.com/Fliplet/fliplet-menu-bottom-bar/pull/31

2020-09-07 14:38 UTC, MaksymShokin commented
@tonytlwu 
I do not see any difference between your video and my video.

2020-09-07 14:45 UTC, tonytlwu commented
Note that in my video when the menu opens, the menu items slide and fade in from the left.

2020-09-08 11:59 UTC, MaksymShokin commented
Fixed https://streamable.com/w92bw3

2020-09-09 17:57 UTC, tonytlwu requested changes

2020-09-09 17:57 UTC, tonytlwu commented on css/menu.css
> +  -webkit-transform: translate3d(0, -100%, 0);
```suggestion
  -webkit-transform: translate3d(0, -100%, 0);
```

2020-09-09 19:37 UTC, MaksymShokin commented on css/menu.css
> +  -webkit-transform: translate3d(0, -100%, 0);
Fixed

2020-09-10 08:53 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Circle app menu
Verify: Menu works as usual

2020-09-10 09:00 UTC, merged